#!/bin/bash
#
#			Joshua Brown
#			October 2016
#
# This script works by first creating a DOCS
# directory. It then looks through all the 
# directories that are in it's current working
# directory. If a .c or a .h file is found the
# program will convert it to a .ps file and
# place the .ps file in /FOLDER/DOCS. In the
# next step all the .ps files will be 
# converted to .pdf files. Finally the .pdf
# files will be merged into a single
# "merged.pdf" file. 
#
# As an example consider the following 
# directory structure
#
# FOLDER/C_CODE_DIR1/file1.c
# FOLDER/C_CODE_DIR1/file1.h
# FOLDER/C_CODE_DIR1/otherfiles.*
# FOLDER/C_CODE_DIR2/file2.c
# FOLDER/C_CODE_DIR2/file2.h
# FOLDER/C_CODE_DIR2/file3.c
# FOLDER/C_CODE_DIR2/file3.h
# FOLDER/C_CODE_DIR2/otherfiles.*
# FOLDER/DIR3/otherfiles.*
#
# Run the scipt in FOLDER
#
# cd FOLDER
# ./doc_create
#
# The final directory structure will look as 
# follows
#
# Here are the old files they are unchanged:
#
# FOLDER/C_CODE_DIR1/file1.c
# FOLDER/C_CODE_DIR1/file1.h
# FOLDER/C_CODE_DIR1/otherfiles.*
# FOLDER/C_CODE_DIR2/file2.c
# FOLDER/C_CODE_DIR2/file2.h
# FOLDER/C_CODE_DIR2/file3.c
# FOLDER/C_CODE_DIR2/file3.h
# FOLDER/C_CODE_DIR2/otherfiles.*
# FOLDER/DIR3/otherfiles.*
#
# Here are the new files:
#
# FOLDER/DOCS/file1.ps
# FOLDER/DOCS/file1h.ps
# FOLDER/DOCS/file2.ps
# FOLDER/DOCS/file2h.ps
# FOLDER/DOCS/file3.ps
# FOLDER/DOCS/file3h.ps
# FOLDER/DOCS/file1.pdf
# FOLDER/DOCS/file1h.pdf
# FOLDER/DOCS/file2.pdf
# FOLDER/DOCS/file2h.pdf
# FOLDER/DOCS/file3.pdf
# FOLDER/DOCS/file3h.pdf
# FOLDER/DOCS/merged.pdf
#

# Step 1 creating DOCS folder
if [ -d 'DOCS' ]
	then
	echo "DOCS File already exists"
else
	mkdir DOCS
fi

dir_list=$(ls -ld -- */ | awk '{print $9}')
DIR="../DOCS/"

# Step 2 looking through all Folders in current 
#		 working directory
#
for dir in $dir_list
do
	echo $dir
	if [ $dir != "DOCS/" ]
		then	
		echo $dir
		cd $dir

		# Step 3 converting .c files to .ps files and 
        #        placing them in DOCS folder
		file_list=$(ls | grep .c)
		file_core_list=$(ls | grep .c | awk '{print substr($0,1,length($0)-2)}')
		for file_core in $file_core_list
		do
			echo $file_core
			file_c=$(echo $file_core".c")
			file_ps=$(echo $DIR$file_core".ps")
			echo $file_ps
			echo $file_c
			enscript -G2r --highlight -o $file_ps $file_c
		done
	
		# Step 4 converting .h files to h.ps files and 
        #        placing them in DOCS folder
		file_list=$(ls | grep .h)
		file_core_list=$(ls | grep .h | awk '{print substr($0,1,length($0)-2)}')
		for file_core in $file_core_list
		do
			echo $file_core
			file_h=$(echo $file_core".h")
			file_ps=$(echo $DIR$file_core"h.ps")
			echo $file_ps
			echo $file_h
			enscript -G2r --highlight -o $file_ps $file_h
		done

		cd ../
	fi	
done

cd "DOCS/"

file_core_list=$(ls | grep .ps | awk '{print substr($0,1,length($0)-3)}')

pdf_list=""

# Step 5 Converting .ps files to .pdf files
for file_core in $file_core_list
	do
	echo $file_core
	file_ps=$(echo $file_core".ps")
	file_pdf=$(echo $file_core".pdf")
	ps2pdf $file_ps $file_pdf
	pdf_list=$(echo $pdf_list" "$file_pdf)	
done

# Step 6 merging all .pdf files to merged.pdf 
pdf_list=$(echo $pdf_list" output merged.pdf")
pdftk $pdf_list 
cd ../	


